DROP database  if exists Sailors;
CREATE database Sailors;
USE Sailors;

CREATE TABLE SAILORS(
    sid INT PRIMARY KEY ,
    sname VARCHAR(20) NOT NULL,
    rating INT,
    age INT,
    check(rating>=1 AND rating<=10)
);

CREATE TABLE BOAT(
    bid INT PRIMARY KEY,
    bname VARCHAR(10) NOT NULL,
    color VARCHAR(10) NOT NULL
);

CREATE TABLE RSERVERS(
    sid INT,
    bid INT,
    FOREIGN KEY(sid) REFERENCES SAILORS(sid) ON DELETE CASCADE,
    FOREIGN KEY(bid) REFERENCES BOAT(bid) ON DELETE CASCADE,
    date DATE
);

INSERT INTO SAILORS VALUES (001, 'Albert', 5, 23);
INSERT INTO SAILORS VALUES (002, 'Bhargav', 4, 25);
INSERT INTO SAILORS VALUES (003, 'Charan', 3, 36);
INSERT INTO SAILORS VALUES (004, 'Astorm', 2, 25);
INSERT INTO SAILORS VALUES (005, 'Varun', 4, 20);

SELECT * FROM SAILORS;

INSERT INTO BOAT VALUES (5001, 'Kayak', 'White');
INSERT INTO BOAT VALUES (5002, 'Jon', 'Grey');
INSERT INTO BOAT VALUES (103, 'Deck', 'White');
INSERT INTO BOAT VALUES (5004, 'Canoe', 'Green');
INSERT INTO BOAT VALUES (5005, 'Windsurf', 'Blue');

SELECT * FROM BOAT;

INSERT INTO RSERVERS VALUES (001, 103, '2024-12-12');
INSERT INTO RSERVERS VALUES (003, 103, '2024-12-12');
INSERT INTO RSERVERS VALUES (002, 5005, '2024-11-12');
INSERT INTO RSERVERS VALUES (004, 103, '2024-12-10');
INSERT INTO RSERVERS VALUES (005, 5004, '2024-11-11');

SELECT * FROM RSERVERS;
